### ISSUE TITLE
Script syntax error

### ISSUE THREAD

**Issue by jonskoglund** [EdwinWenink/kobo-notes#1]
Hello Edwin. I was playing with your script. After installing Python and the BeautifulSoup module I tried this command: `python ./kobo_export.py --help` Unfortunately I got this error:

```
File "./kobo_export.py", line 104
    with open(f"{output_dir}{filename}.md", "w", encoding="utf-8") as output:
                                         ^
SyntaxError: invalid syntax
iMac:kobo-notes-main johns$ python ./kobo_export.py --help
  File "./kobo_export.py", line 104
    with open(f"{output_dir}{filename}.md", "w", encoding="utf-8") as output:
                                         ^
SyntaxError: invalid syntax 
```
I'm not so fluent in Python so my question is: how do I fix this error?

**Comment by EdwinWenink** [comment]
Hi! My first guess would be that you don't have the correct version of Python because these "format strings" were only introduced in Python 3.6. If you type ` python --version ` in your command line, which version do you see?

If that's the issue, I'll update the README with a note that you require python 3.6 :-)

**Comment by EdwinWenink** [comment]
@jonskoglund can I close this?
